import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

/** @type {import("eslint").Linter.Config[]} */
const config = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "node_modules/**",
      // Aceternity UI — auto-generated by pnpm setup-ui; never edited directly
      "components/ui/**",
      "hooks/**",
      "components/**-demo.tsx",
      // Next.js generated type declaration
      "next-env.d.ts",
      // Independently deployed Cloudflare Worker — own tsconfig/lint scope
      "workers/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "no-console": ["warn", { allow: ["warn", "error", "log"] }],
      "@typescript-eslint/no-explicit-any": "error",
      // Allow _ prefix to mark intentionally unused parameters / variables
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "import/no-default-export": "off",
    },
  },
  {
    files: ["scripts/**/*.ts"],
    rules: {
      "no-console": "off",
    },
  },
];

export default config;
